//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoAjaxSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauThu
    {
        public string macauthu { get; set; }
        public string tencauthu { get; set; }
        public string email { get; set; }
        public string sodt { get; set; }
        public string madoibong { get; set; }
    }
}
